#!/usr/bin/env python3
"""런타임별 서브 에이전트 선언 파일을 공통 프로필·모델표에서 생성한다.

`.codex/config.toml`, `.codex/agents/*.toml`, `.claude/agents/*.md`는 손으로 쓰지
않는다. 모델이나 지시문을 바꾸려면 execution_profiles.py의 표를 고치고 이 스크립트를
다시 실행한다. 검증기는 생성 결과와 실제 파일이 어긋나면 오류를 낸다.

    python scripts/sync_runtime_agents.py          # 생성·갱신
    python scripts/sync_runtime_agents.py --check  # 어긋난 파일이 있으면 종료 코드 1
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    from .execution_profiles import (
        AGENT_DESCRIPTIONS,
        AGENT_INSTRUCTIONS,
        EXECUTION_PROFILES,
        RUNTIME_MODEL_TABLES,
        SUBAGENT_CONCURRENCY_LIMIT,
        SUBAGENT_PROFILES,
    )
except ImportError:  # `python scripts/sync_runtime_agents.py`로 직접 실행할 때
    from execution_profiles import (
        AGENT_DESCRIPTIONS,
        AGENT_INSTRUCTIONS,
        EXECUTION_PROFILES,
        RUNTIME_MODEL_TABLES,
        SUBAGENT_CONCURRENCY_LIMIT,
        SUBAGENT_PROFILES,
    )

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

PROJECT_ROOT = Path(__file__).resolve().parent.parent
CLAUDE_AGENT_TOOLS = "Read, Write, Edit, Grep, Glob, Bash"


def agent_file_stem(agent: str) -> str:
    return agent.replace("_", "-")


def render_codex_config() -> str:
    default = RUNTIME_MODEL_TABLES["codex"]["economy_high"]
    return (
        "[agents]\n"
        "enabled = true\n"
        f"max_concurrent_threads_per_session = {SUBAGENT_CONCURRENCY_LIMIT}\n"
        f'default_subagent_model = "{default["model"]}"\n'
        f'default_subagent_reasoning_effort = "{default["effort"]}"\n'
    )


def render_codex_agent(profile: str) -> str:
    agent = EXECUTION_PROFILES[profile]["agent"]
    row = RUNTIME_MODEL_TABLES["codex"][profile]
    instructions = AGENT_INSTRUCTIONS[agent]
    if '"""' in instructions:
        raise ValueError(f"{agent} 지시문에 TOML 구분자 \"\"\"가 들어 있습니다.")
    return (
        f'name = "{agent}"\n'
        f'description = "{AGENT_DESCRIPTIONS[agent]}"\n'
        f'model = "{row["model"]}"\n'
        f'model_reasoning_effort = "{row["effort"]}"\n'
        'developer_instructions = """\n'
        f"{instructions}"
        '"""\n'
    )


def render_claude_agent(profile: str) -> str:
    agent = EXECUTION_PROFILES[profile]["agent"]
    row = RUNTIME_MODEL_TABLES["claude"][profile]
    return (
        "---\n"
        f"name: {agent}\n"
        f"description: {AGENT_DESCRIPTIONS[agent]} Execution profile {profile}; invoke only when the manager assigns a bounded packet and output path.\n"
        f"tools: {CLAUDE_AGENT_TOOLS}\n"
        f"model: {row['model']}\n"
        f"effort: {row['effort']}\n"
        "---\n"
        "\n"
        f"# {agent} ({profile})\n"
        "\n"
        "This definition is generated by `scripts/sync_runtime_agents.py` from the shared execution-profile table. "
        "Edit the table, not this file. Role-specific duties live in `agent_prompts/`; the manager names the role prompt, "
        "the evidence packet, predecessor artifacts, and the output path in the invocation.\n"
        "\n"
        f"{AGENT_INSTRUCTIONS[agent]}"
    )


def expected_files(root: Path) -> dict[Path, str]:
    files: dict[Path, str] = {root / ".codex" / "config.toml": render_codex_config()}
    for profile in SUBAGENT_PROFILES:
        stem = agent_file_stem(EXECUTION_PROFILES[profile]["agent"])
        files[root / ".codex" / "agents" / f"{stem}.toml"] = render_codex_agent(profile)
        files[root / ".claude" / "agents" / f"{stem}.md"] = render_claude_agent(profile)
    return files


def drift_report(root: Path) -> list[str]:
    """생성 결과와 실제 파일이 어긋난 곳을 사람이 읽을 문장으로 돌려준다. 비어 있으면 일치."""
    problems: list[str] = []
    expected = expected_files(root)
    for path, content in expected.items():
        if not path.is_file():
            problems.append(f"없음: {path}")
        elif path.read_text(encoding="utf-8") != content:
            problems.append(f"표와 다름: {path}")
    for agent_dir, suffix in ((root / ".codex" / "agents", ".toml"), (root / ".claude" / "agents", ".md")):
        if agent_dir.is_dir():
            for stray in sorted(agent_dir.glob(f"*{suffix}")):
                if stray not in expected:
                    problems.append(f"표에 없는 선언: {stray}")
    return problems


def sync(root: Path) -> list[Path]:
    written: list[Path] = []
    for path, content in expected_files(root).items():
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.is_file() or path.read_text(encoding="utf-8") != content:
            path.write_text(content, encoding="utf-8", newline="\n")
            written.append(path)
    return written


def main() -> int:
    parser = argparse.ArgumentParser(description="런타임별 서브 에이전트 선언을 공통 모델표와 동기화합니다.")
    parser.add_argument("--root", type=Path, default=PROJECT_ROOT)
    parser.add_argument("--check", action="store_true", help="파일을 쓰지 않고 어긋난 곳만 보고합니다.")
    args = parser.parse_args()
    root = args.root.expanduser().resolve()
    if args.check:
        problems = drift_report(root)
        for problem in problems:
            print(f"[DRIFT] {problem}")
        print("런타임 선언: " + ("일치" if not problems else f"어긋남 {len(problems)}개"))
        return 1 if problems else 0
    written = sync(root)
    for path in written:
        print(f"갱신: {path.relative_to(root)}")
    print(f"런타임 선언 {len(expected_files(root))}개 동기화 완료 (변경 {len(written)}개)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
